### ISSUE TITLE
Change the screen size

### ISSUE THREAD

**Issue by afzalhmd14** [krishraghuram/mess#11]
Attach bigger screen

**Comment by krishraghuram** [comment]
Yep. We will do that as follows. 

1. Version 1.x has 5-point rating scale for each meal. 
2. Current master has the HAB format of the feedback(once a month, on five different categories).
We will branch this into Version 2.x
3. Then, master will be updated with instructions for the 7 inch HDMI screen. 

Comments?

**Comment by krishraghuram** [comment]
The 7 inch HDMI screen we have is made by waveshare(or a clone). 
This is the guide to set it up for rpi. Nothing complicated. Just need to add a few lines to /boot/config.txt

https://www.waveshare.com/wiki/7inch_HDMI_LCD_(B)#Working_with_Raspberry_Pi

**Comment by krishraghuram** [comment]
Updated mess-rpisetup project with instructions for waveshare 7 inch screen in commit https://github.com/krishraghuram/mess-rpisetup/commit/e6f748edd845e1fc0f9e49d2dfad4c0aaddffc84

mess-rpisetup now has two branches. `waveshare3.5` with instructions for 3.5 inch screen and `waveshare7` with instructions for 7 inch screen. 

Updated Readme.md in master with instructions for setting up 7 inch screen. 

Backport needed for updating Readme.md in version1.x
